kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: vaibhavrajput/flask-k8s-demo:latest
        command: ["python"]
        args: ["app.py"]
        ports:
        - containerPort: 5001
